# Generated by Django 4.0.5 on 2022-07-04 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webProyecto2app', '0002_calificaciones_alumno_grupo_alumno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alumno',
            old_name='name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='tel',
            new_name='dni',
        ),
        migrations.RenameField(
            model_name='alumno',
            old_name='turno',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='calificaciones',
            old_name='media',
            new_name='notaFinal',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='profesor',
            old_name='tel',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='email',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='name',
        ),
        migrations.RemoveField(
            model_name='calificaciones',
            name='tel',
        ),
        migrations.AlterField(
            model_name='alumno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
